### ISSUE TITLE
Index Out of Bounds Error on gcp-cname.py

### ISSUE THREAD

**Issue by gray-host** [domain-protect/domain-protect-gcp#60]
Feel free to close this if it's an issue with the way I'm running the program.

When I first tried to run gcp-cname.py locally, I kept getting IOB errors related to [the loop on line 55-60](https://github.com/domain-protect/domain-protect-gcp/blob/main/manual-scans/gcp-cname.py#L55-L60).  After doing some debugging it seems like this was thrown due to some records sets returning empty lists in rrdatas.  I fixed this locally by removing the [0] index altogether and having the any() check look through the entire rrdatas list instead of a specific index.

LMK if this was intentional and I've broken the script now.

**Comment by paulschwarzenberger** [comment]
@gray-host thanks for raising this issue, and apologies for not replying earlier!
The code as it is resulted from the test data used which must have all contained at least one item in the list. I know it's been a while, however, would you like to submit a PR?

**Comment by gray-host** [comment]
Will do
