### ISSUE TITLE
GCP manual CNAME scan looking for Azure domains?

### ISSUE THREAD

**Issue by cleo2525** [domain-protect/domain-protect-gcp#73]
I'm trying out domain-protect-gcp and I noticed that the CNAME manual scan, gcp-cname.py, seems to be looking for Azure domains. Is that correct?

vulnerability_list = [
    "azure",
    ".cloudapp.net",
    "core.windows.net",
    "elasticbeanstalk.com",
    "trafficmanager.net",
]

**Comment by paulschwarzenberger** [comment]
yes, this is intentional to cover the case of a DNS record in Google Cloud DNS pointing to a resource in another cloud.
